### ISSUE TITLE
Source code severely out of date

### ISSUE THREAD

**Issue by mvdan** [Stericson/busybox-free#7]
The play store has version 37, updated in December: https://play.google.com/store/apps/details?id=stericson.busybox

But this repo only has up to version 25.

If you moved the source somewhere else, could you point me to it?

**Comment by mvdan** [comment]
Reping @Stericson

**Comment by Skeptyc** [comment]
@Stericson Hey wake up.  Fulfil your license obligations. I downloaded your app on Google Play, and according to the License I can request the current source, so please provide it.

**Comment by Stericson** [comment]
@mvdan @Skeptyc Sorry guys, I'll update the source this week.

**Comment by Skeptyc** [comment]
@Stericson Thank you very much :)

**Comment by Stericson** [comment]
Updated
